### ISSUE TITLE
How to Reference PR

### ISSUE THREAD

**Issue by ericdrosado** [xaca/individual-work#3]
@xaca you can reference PR #2 like this by using `#` and the number of the PR. You can determine the number of the PR by looking at the number next to the title of the PR: 
<img width="521" alt="Screen Shot 2019-05-14 at 10 01 51 AM" src="https://user-images.githubusercontent.com/10368374/57708648-58640080-762f-11e9-9e2f-262a27151ae9.png">

**Comment by xaca** [comment]
@ericdrosado Thank you, nice tip :muscle:
